config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "static_pages#index"
  
  get 'about', to: 'static_pages#about'
  get 'contact_page', to: 'static_pages#contact_page'
  get 'log_in', to: 'sessions#new'
  post 'log_in', to: 'sessions#create'
  delete 'log_out', to: 'sessions#destroy'
    
  resources :contacts
  resources :users, only: [:new, :create, :show, :edit, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :name, presence: true, length: { maximum: 50 }
  validates :phone, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :password, length: { minimum: 6 }
  validates :email, presence: true, length: { maximum: 255 }, 
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: true }

  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_logged_in_user
    unless user_signed_in?
      flash[:danger] = 'Área restrita. Por favor, realize o login'
      redirect_to log_in_path
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contato criado com sucesso.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contato alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contato excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = current_user.contacts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to user_path(current_user) if user_signed_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to contacts_path
    else
      flash.now[:danger] = 'Email ou Senha inválidos'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = 'Saiu com sucesso!'
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def about
  end

  def contact_page
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:sucess] = 'Usuário cadastrado com sucesso'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      flash[:success] = "Dados atualizados com sucesso!"
      redirect_to contacts_url
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= render 'layouts/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :phone %>
  <%= f.text_field :phone, class: "form-control" %>
</div>

app/views/contacts/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Editar Contato</h1>
  </div>

  <div class="col-md-6 offset-md-3 col-xs-12">
    <%= form_for @contact do |f| %>
      <%= render 'form', f: f %>

      <%= f.submit 'Atualizar', class: 'btn btn-primary' %>
    <% end %>
  </div>  
</div>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h1>Meus contatos</h1>
  </div>

  <div class="col-md-8 offset-md-2 col-xs-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Telefone</th>
          <th colspan="2">
            Ações
            <%= link_to "<i class='fa fa-file' title='Novo Contato'></i>"
                .html_safe, new_contact_path, class: "btn btn-success" %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% if @contacts.empty? %>
          <tr>
            <td colspan="4" class="text-center">
              <h3>Sem contatos cadastrados.</h3>
              <%= link_to 'click aqui', new_contact_path %> para cadastrar um novo contato
            </td>
          </tr>
        <% end %>
        <% @contacts.each do |c| %>
          <tr>
            <td>
              <%= c.name %>
            </td>
            <td>
              <%= c.phone %>
            </td>
            <td>
              <%= link_to "<i class='fa fa-edit ' title='Editar'></i>"
                  .html_safe, edit_contact_path(c), class: 'btn btn-warning' %>
              
            </td>
            <td>
              <%= link_to "<i class='fa fa-trash-alt' title='Excluir'></i>"
                  .html_safe, contact_path(c), method: :delete, 
                  class: 'btn btn-danger', data: { confirm: 'Tem certeza' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Adicionar Novo Contato</h1>
  </div>

  <div class="col-md-6 offset-md-3 col-xs-12">
    <%= form_for @contact do |f| %>
      <%= render 'form', f: f %>

      <%= f.submit 'Salvar', class: 'btn btn-primary' %>
    <% end %>
  </div>  
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <div class="alert alert-danger">
      Oops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <%= link_to 'Contatc List. Todos os direitos reservados', root_path %>
  </small>

  <nav>
    <ul>
      <li>
        <%= link_to 'Sobre', about_path %>
      </li>
      <li>
        <%= link_to 'Contato', contact_page_path %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="header-content">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

    <div class="container-fluid">
      <%= link_to 'Contact List', '/', class: "navbar-brand" %>

      <div class="navbar-header">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      </div>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <% unless user_signed_in? %>
            <li class="active">
              <%= link_to 'Nova Conta', new_user_path, class: "nav-link"%>
            </li>
          <% end %>
        </ul>

        <ul class="navbar-nav navbar-right">

          <% unless user_signed_in? %>
            <li class="nav-item active">
              <%= link_to 'Entrar', log_in_path, class: "nav-link"  %>
            </li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="btn btn-secondary dropdown-toggle bg-dark" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Bem Vindo! <%= current_user.name %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Minha Pagina', contacts_path, class:"dropdown-item"  %>
                </li>
                <li>
                  <%= link_to 'Editar', edit_user_path(current_user), class:"dropdown-item" %>
                </li>
                <div class="dropdown-divider"></div>
                <li>
                  <%= link_to 'Sair', log_out_url, method: :delete, class:"dropdown-item" %>
                </li>
              </ul>
            </li>
          <% end %>

        </ul>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ContactList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">

    <link rel="manifest" href="/manifest.json" />

  </head>

  <body>
    <%= render 'layouts/header'%>

    <div class="container">

    <% flash.each do |message_type, message| %>
      <%= content_tag 'div', class: "alert alert-#{message_type} alert-success", role: 'alert' do %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= message %>
      <% end %>
    <% end %>

      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>Sobre</h1>

<p>
  Criado com o intuito de ensinar um pouco sobre o Framework Ruby on Rails, Contact List mostrará como aprender as peças que formam essa ferramenta tão poderosa.
</p>

app/views/static_pages/contact.html.erb
<br><br><br>
<h1>Contato</h1>

<p>
  Entre em contato com <a href="#">@barufi</a> para saber mais.
</p>

app/views/static_pages/contact_page.html.erb
<h1>Contato</h1>

<p>
  Entre em contato com <a href="#">@barufi</a> para saber mais.
</p>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Contact List</h1>
  <p class="lead">
    Gerencie seus cotatos em qual quer lugar!
  </p>

<% unless user_signed_in? %>
  <p>
    <%= link_to 'Crie sua Conta', new_user_path, class: 'btn btn-primary btn-lg' %>
  </p>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= render 'layouts/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Editar dados</h1>
  </div>

  <div class="col-md-6 offset-md-3 col-sx-12">
    <%= form_for current_user do |f| %>
    
      <%= render 'form', f: f %>

      <%= f.submit 'cadastar', class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Cadastre-se</h1>
  </div>

  <div class="col-md-6 offset-md-3 col-sx-12">
    <%= form_for @user do |f| %>
      <%= render 'layouts/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'cadastar', class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Bem vindo!<%= current_user.name %></h1>